spring:
  datasource:
    url: jdbc:mysql://awseb-e-3dpp3eadki-stack-awsebrdsdatabase-tz2z2uew9vnk.cji2juqgjzga.ap-northeast-2.rds.amazonaws.com:3306
    username: practice
    password: qwer1234!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100